---
name: Release
on:
  push:
    tags:
      - v*
jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            app_version=${{ github.ref_name }}
          tags: |
            ghcr.io/benjaminbartels/scoutbot:latest
            ghcr.io/benjaminbartels/scoutbot:${{ github.ref_name }}
